### ISSUE TITLE
Crash when cleaning large project

### ISSUE THREAD

**Issue by sash** [mvisonneau/docker-registry-gitlab-cleanup#7]
Hi and thanks for the great project! We really need something like this since we don't really use the omnibus package and we don't have access to gitlab-ctl!

The crash we experienced was while the tool was indexing a large registry. Here is the crash itself:

Traceback (most recent call last):
  File "/usr/local/bin/rgc", line 11, in <module>
    load_entry_point('rgc==0.1.0', 'console_scripts', 'rgc')()
  File "/usr/local/lib/python3.7/site-packages/rgc-0.1.0-py3.7.egg/rgc/cli.py", line 22, in main
  File "/usr/local/lib/python3.7/site-packages/rgc-0.1.0-py3.7.egg/rgc/gitlab/clean.py", line 38, in clean_projects
TypeError: object of type 'NoneType' has no len()

**Comment by sash** [comment]
I will be penguin up a fork, and I will try and solve the problem
